# Generated by Django 2.2.1 on 2019-07-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='biling_profile',
            new_name='billing_profile',
        ),
    ]
