# Generated by Django 2.2.1 on 2019-07-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingprefernce',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
